import { Category } from "./entities";

export const CONNECTIONS = {
  mysql: {
    normal: {
      type: "mysql",
      host: "localhost",
      port: 3307,
      username: "root",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "mysql",
      host: "localhost",
      port: 3306,
      username: "root",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
  },
  postgres: {
    normal: {
      type: "postgres",
      host: "localhost",
      port: 5433,
      username: "postgres",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "postgres",
      host: "localhost",
      port: 5432,
      username: "postgres",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
  },
  sqlserver: {
    normal: {
      type: "mssql",
      host: "localhost",
      port: 1434,
      username: "sa",
      password: "StrongPassw0rd",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "mssql",
      host: "localhost",
      port: 1433,
      username: "sa",
      password: "StrongPassw0rd",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
  },
};
