import { Category, CategoryMongoDB } from "./entities";

export const CONNECTIONS = {
  mysql: {
    normal: {
      type: "mysql",
      host: "localhost",
      port: 3307,
      username: "root",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "mysql",
      host: "localhost",
      port: 3306,
      username: "root",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
  },
  postgres: {
    normal: {
      type: "postgres",
      host: "localhost",
      port: 5433,
      username: "postgres",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "postgres",
      host: "localhost",
      port: 5432,
      username: "postgres",
      password: "root",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
  },
  sqlserver: {
    normal: {
      type: "mssql",
      host: "localhost",
      port: 1434,
      username: "sa",
      password: "StrongPassw0rd",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
      options: { encrypt: false },
    },
    tmpfs: {
      type: "mssql",
      host: "localhost",
      port: 1433,
      username: "sa",
      password: "StrongPassw0rd",
      database: "fullcycle",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
      options: { encrypt: false },
    },
  },
  mongo: {
    normal: {
      type: "mongodb",
      host: "localhost",
      port: 27018,
      username: "root",
      password: "root",
      database: "fullcycle",
      authSource: 'admin',
      synchronize: true,
      logging: false,
      entities: [CategoryMongoDB],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "mongodb",
      host: "localhost",
      port: 27017,
      username: "root",
      password: "root",
      database: "fullcycle",
      authSource: 'admin',
      synchronize: true,
      logging: false,
      entities: [CategoryMongoDB],
      subscribers: [],
      migrations: [],
    },
  },
  oracle: {
    normal: {
      type: "oracle",
      host: "oracle",
      port: 1521,
      username: "system",
      password: "root",
      database: "free",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
    tmpfs: {
      type: "oracle",
      host: "oracle_tmpfs",
      port: 1521,
      username: "system",
      password: "root",
      database: "free",
      synchronize: true,
      logging: false,
      entities: [Category],
      subscribers: [],
      migrations: [],
    },
  }
};
